const icons = '/assets/symbols/casino-page.svg'

export const JUNGLEBET_ORIGINALS_ICON = `${icons}#junglebetOriginals`
export const TABLE_GAMES_ICON = `${icons}#tableGames`
export const GAME_SHOWS_ICON = `${icons}#gameShows`
export const FEATURED_SLOTS_ICON = `${icons}#featuredSlots`
export const DICE_ICON = `${icons}#dice`
export const LIMBO_ICON = `${icons}#limbo`
export const LIVE_CASINO_ICON = `${icons}#liveCasino`
export const CASINO_LOBBY_ICON = `${icons}#lobby`
export const CASINO_MINE_ICON = `${icons}#mine`
export const BLACKJACK_ICON = `${icons}#blackJack`
export const POKER_ICON = `${icons}#pokerIcon`
export const ROULETTE_ICON = `${icons}#roulette`
export const BACCARAT_ICON = `${icons}#baccarat`
export const BETS_TICKET_ICON = `${icons}#betsTicketIcon`
export const ALL_BETS_ICON = `${icons}#allBetsIcon`
export const TOP_CROWN_ICON = `${icons}#topCrownIcon`
export const TOP_FIVE_CUP_ICON = `${icons}#goldenCupIcon`
