export const LANGUAGES = [
  { display: 'English', lang: 'en', icon: 'i-circle-flags-us' },
  { display: '汉语', lang: 'zh', icon: 'i-circle-flags-cn' },
  { display: 'Hindi', lang: 'hi', icon: 'i-circle-flags-in' },
  { display: 'Español', lang: 'es', icon: 'i-circle-flags-es' },
  { display: 'Français', lang: 'fr', icon: 'i-circle-flags-fr' },
  { display: 'لعربية الفصحى', lang: 'ar', icon: 'i-circle-flags-ar' },
  { display: 'বাংলা', lang: 'bn', icon: 'i-circle-flags-bd' },
  { display: 'Русский', lang: 'ru', icon: 'i-circle-flags-ru' },
  { display: 'Português', lang: 'pt', icon: 'i-circle-flags-pt' },
  { display: 'اُردُو', lang: 'ur', icon: 'i-circle-flags-pk' },
  { display: 'Bahasa Indonesia', lang: 'id', icon: 'i-circle-flags-id' },
  { display: 'Deutsch', lang: 'de', icon: 'i-circle-flags-de' },
  { display: '日本語', lang: 'ja', icon: 'i-circle-flags-jp' },
  { display: 'Filipino', lang: 'fil', icon: 'i-circle-flags-ph' },
  { display: 'هَوُسَ', lang: 'ha', icon: 'i-circle-flags-ng' },
  { display: 'मराठी', lang: 'mr', icon: 'i-circle-flags-mr' },
  { display: 'తెలుగు', lang: 'te', icon: 'i-circle-flags-za' },
  { display: 'Türkçe', lang: 'tr', icon: 'i-circle-flags-tr' },
  { display: 'தமிழ்', lang: 'ta', icon: 'i-circle-flags-my' },
  { display: 'Tiếng Việt', lang: 'vi', icon: 'i-circle-flags-vn' },
  { display: '廣東話', lang: 'yue', icon: 'i-circle-flags-hk' },
  { display: 'ภาษาไทย', lang: 'th', icon: 'i-circle-flags-th' },
  { display: 'සිංහල', lang: 'si', icon: 'i-circle-flags-lk' },
]
